// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfwyJwSNPxQSEBi1XaM52tDN4AsDgUs1k',
    appId: '1:167633517271:web:15b1a6f5ec5e41a56a8e92',
    messagingSenderId: '167633517271',
    projectId: 'chat-103ab',
    authDomain: 'chat-103ab.firebaseapp.com',
    storageBucket: 'chat-103ab.firebasestorage.app',
    measurementId: 'G-ZHNPEMDTF7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOAP9vDsXY_LRcG6X4hQPlBURZuv7MQlY',
    appId: '1:167633517271:android:d2caccb532fb30306a8e92',
    messagingSenderId: '167633517271',
    projectId: 'chat-103ab',
    storageBucket: 'chat-103ab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPuMVvSQbNQYUQQD2T65t5qR0IiYuqslY',
    appId: '1:167633517271:ios:b7ebcafc4ba8a48e6a8e92',
    messagingSenderId: '167633517271',
    projectId: 'chat-103ab',
    storageBucket: 'chat-103ab.firebasestorage.app',
    iosBundleId: 'com.example.scholarChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPuMVvSQbNQYUQQD2T65t5qR0IiYuqslY',
    appId: '1:167633517271:ios:b7ebcafc4ba8a48e6a8e92',
    messagingSenderId: '167633517271',
    projectId: 'chat-103ab',
    storageBucket: 'chat-103ab.firebasestorage.app',
    iosBundleId: 'com.example.scholarChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfwyJwSNPxQSEBi1XaM52tDN4AsDgUs1k',
    appId: '1:167633517271:web:8db9cab469ffa12f6a8e92',
    messagingSenderId: '167633517271',
    projectId: 'chat-103ab',
    authDomain: 'chat-103ab.firebaseapp.com',
    storageBucket: 'chat-103ab.firebasestorage.app',
    measurementId: 'G-1RF4VS417J',
  );
}
